/**
 * Constantes des IDs de types d'utilisateurs
 * Source unique de verite — importer depuis ce fichier partout
 */
const TYPE_USER_IDS = {
  VISITEUR: 1,
  ECRIVAIN: 2,
  JOURNALISTE: 3,
  SCIENTIFIQUE: 4,
  ACTEUR: 5,
  ARTISTE: 6,
  ARTISAN: 7,
  REALISATEUR: 8,
  MUSICIEN: 9,
  PHOTOGRAPHE: 10,
  DANSEUR: 11,
  SCULPTEUR: 12,
  AUTRE: 13,
  POETE: 14,   // migration 20260331-add-poete-conteur-types
  CONTEUR: 15,
  ADMINISTRATEUR: 29
};

// Types qu'un visiteur peut choisir lui-meme a l'inscription
// (aligne sur SECTEUR_TYPE_USER_MAP du frontend). ADMINISTRATEUR en est exclu.
const REGISTRABLE_TYPE_USER_IDS = new Set([
  TYPE_USER_IDS.VISITEUR, TYPE_USER_IDS.ECRIVAIN, TYPE_USER_IDS.JOURNALISTE,
  TYPE_USER_IDS.SCIENTIFIQUE, TYPE_USER_IDS.ACTEUR, TYPE_USER_IDS.ARTISTE,
  TYPE_USER_IDS.ARTISAN, TYPE_USER_IDS.REALISATEUR, TYPE_USER_IDS.MUSICIEN,
  TYPE_USER_IDS.PHOTOGRAPHE, TYPE_USER_IDS.DANSEUR, TYPE_USER_IDS.SCULPTEUR,
  TYPE_USER_IDS.AUTRE, TYPE_USER_IDS.POETE, TYPE_USER_IDS.CONTEUR
]);

module.exports = { TYPE_USER_IDS, REGISTRABLE_TYPE_USER_IDS };
